apps/core/urls.py
from django.conf.urls import url

from apps.core.api import DealListAPIView, HubTokenAPIView
from apps.core.views import IndexView, ListDealView

urlpatterns = [
    url(r'^get-code/$', IndexView.as_view(), name='get_code'),
    url(r'^list-deals-api/$', DealListAPIView.as_view(), name='list_deals_api'),
    url(r'^get-token/$', HubTokenAPIView.as_view(), name='get_token'),
    url(r'^$', ListDealView.as_view(), name='index'),
]

config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('apps.core.urls', 'core'), namespace='core')),
]

apps/core/models.py
from django.db import models


class Deal(models.Model):
    deal_id = models.IntegerField()
    deal_name = models.CharField(max_length=250, blank=True, null=True)
    deal_stage = models.CharField(max_length=250, blank=True, null=True)
    close_date = models.DateTimeField(blank=True, null=True)
    amount = models.DecimalField(max_digits=19, decimal_places=2, blank=True, null=True)
    deal_type = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.deal_id)


class HubToken(models.Model):
    access_token = models.TextField()
    refresh_token = models.TextField(blank=True, null=True)
    expires_in = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.access_token)

apps/core/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'usuario': False,
        })
        return context


class ListDealView(TemplateView):
    template_name = 'list_deals.html'
    context_object_name = 'deals'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'parameter_search': self.request.GET.get('parameter_search', '').strip(),
            'token': self.request.GET.get('token', '')
        })
        return context

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<a href="https://app.hubspot.com/oauth/authorize?client_id=962c9f97-2aaf-40fa-96e1-75224cd67261&redirect_uri=http://localhost:8000/get-code&scope=contacts%20content%20reports%20oauth%20crm.import">Install</a>

</body>
</html>

templates/list_deals.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Challenge Globant</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <div class="panel panel-primary" style="margin-left: 10%">
      <div class="panel-heading">List deals</div>
        <div class="panel-body">
          <form action="" class="inline-group" method="GET">
            <div class="row">
              <div class="col-xs-3">
                <label>Access token Hubspot</label>
              </div>
              <div class="col-xs-9">
                <input id="token" name="token" type="text" class="textinput textInput form-control" required value="{{ token }}">
              </div>
            </div>
            <div class="row">
              <div class="col-xs-3">
                <label>Id/name/stage/type</label>
              </div>
              <div class="col-xs-9">
                <input id="parameter_search" name="parameter_search" type="text" class="textinput textInput form-control" required value="{{ parameter_search }}">
              </div>
              <div class="col-xs-2">
                <button type="submit" class="btn btn-info" id="btn_search"> <i class="fa fa-search"></i> Search</button>
              </div>
            </div>
          </form>
          <hr>
          <table class="table table-responsive table-hover table-striped table-bordered" id="table" style="width: 100%;display: inline-block;">
            <thead class="custom-header">
              <tr>
                <th style="width: 5%">Id</th>
                <th>Name</th>
                <th>Stage</th>
                <th style="width: 35%">Close date</th>
                <th>Amount</th>
                <th>Type</th>
              </tr>
            </thead>
          </table>
        </div>
      </div>

  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
  <script>
    var urlDataBusqueda = "{% url 'core:list_deals_api' %}?parameter_search={{ parameter_search|safe }}?token={{ token|safe }}";
    var urlData = "{% url 'core:list_deals_api' %}?";
    $(document).ready(function () {
      parameterSearch = $("#parameter_search");
      token = $("#token");
      buttonSearch = $("#btn_search");
      var tabla = "";
      if ($("#table").length){
        tabla = $("#table").DataTable({
          "processing": true,
          "bSort": false,
          "searching": false,
          "pagingType": "full_numbers",
          "serverSide": true,
          "ajax"      : urlDataBusqueda,
          "language":{
            "sLoadingRecords": "Loading...",
            "sProcessing": "Loading...",
          }
        });
      }


      buttonSearch.on("click", function (e) {
        e.preventDefault();
        tabla.ajax.url(urlData + "parameter_search=" + parameterSearch.val() + "&token=" + token.val()
        ).load();
      })

    });

  </script>

  </body>
</html>